/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe_I;
import javax.swing.JOptionPane; //libreria
import java.util.Locale; //lib de idioma
import javax.swing.UIManager;
import java.awt.EventQueue;



/**
 *
 * @author Refill
 */
public class cuadro_de_verificacion_ej1 extends javax.swing.JFrame {

    /**
     * Creates new form cuadro_de_verificacion_ej1
     */
    public cuadro_de_verificacion_ej1() {
        //constructor
        initComponents();
        this.setLocationRelativeTo(null); //centrar
        this.setSize(400,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcb_hp = new javax.swing.JCheckBox();
        jcb_dell = new javax.swing.JCheckBox();
        jcb_acer = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        eti_resultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcb_hp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_hp.setText("Hp");
        getContentPane().add(jcb_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jcb_dell.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_dell.setText("Dell");
        getContentPane().add(jcb_dell, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jcb_acer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcb_acer.setText("Acer");
        getContentPane().add(jcb_acer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Marcas de PCs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        eti_resultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensaje"));
        getContentPane().add(eti_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 220, 40));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setForeground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mensaje = "La marca seleccionada es --> ";
        if (jcb_hp.isSelected()){
            mensaje = mensaje + "Hp"; 
        }
        else if (jcb_dell.isSelected()){
            mensaje = mensaje + "Dell"; 
        }
        else if (jcb_acer.isSelected()){
            mensaje = mensaje + "Acer"; 
        }
        eti_resultado.setText(mensaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        //dispose(); //cerrar ventanas
        //System.exit(0);// cerrar formularios
        
        //Locale.setDefault(new Locale("es","ES"));
        //int cerrar_ventana = JOptionPane.showConfirmDialog(rootPane, "Deseas salir del ejercicio","Atencion",JOptionPane.YES_NO_OPTION);
        
        // OPCIONES SI NO EN ESPAÑOL
        UIManager.put("OptionPane.yesButtonText","Si");
        UIManager.put("OptionPane.noButtonText","No");
        
        EventQueue.invokeLater(()->{
            int cerrar_ventana = JOptionPane.showConfirmDialog(null, "Deseas salir del ejercicio","Atencion",JOptionPane.YES_NO_OPTION);
            if (cerrar_ventana == JOptionPane.YES_OPTION){
            //System.exit(0);
            dispose();
            }
        });    
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuadro_de_verificacion_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuadro_de_verificacion_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuadro_de_verificacion_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuadro_de_verificacion_ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuadro_de_verificacion_ej1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel eti_resultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcb_acer;
    private javax.swing.JCheckBox jcb_dell;
    private javax.swing.JCheckBox jcb_hp;
    // End of variables declaration//GEN-END:variables
}
