/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Edgar
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form acceso
     */
    public login() {
        //Constructor
        initComponents();
        this.setLocationRelativeTo(this);
        mostrarTiempo();
    }
    
    //LLAMANDO OBJETO TIEMPOR PARA FECHA
    Tiempo time = new Tiempo(); 
    
    //FECHA EN JLABEL
    //Creando metodo --> debe estar llamado en el bloque de init del formulario
    public void mostrarTiempo(){
       label_fecha.setText(time.fechacompleta);
       label_hora.setText(time.horacompleta);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTitulo = new javax.swing.JLabel();
        label_fecha = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        btn_acceder = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 300));
        setPreferredSize(new java.awt.Dimension(382, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTitulo.setFont(new java.awt.Font("Century Gothic", 3, 30)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTitulo.setText("Acceso al sistema");
        jPanel3.add(jTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 28));

        label_fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_fecha.setForeground(new java.awt.Color(255, 255, 255));
        label_fecha.setText("99-99-9999");
        label_fecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                label_fechaPropertyChange(evt);
            }
        });
        jPanel3.add(label_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        label_hora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_hora.setForeground(new java.awt.Color(255, 255, 255));
        label_hora.setText("99:99");
        jPanel3.add(label_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 84));

        txt_user.setForeground(new java.awt.Color(102, 102, 102));
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userKeyTyped(evt);
            }
        });
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, 30));

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 30));

        btn_acceder.setBackground(new java.awt.Color(51, 102, 255));
        btn_acceder.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_acceder.setForeground(new java.awt.Color(255, 255, 255));
        btn_acceder.setText("Acceder");
        btn_acceder.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });
        btn_acceder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_accederKeyPressed(evt);
            }
        });
        getContentPane().add(btn_acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 190, 35));

        btn_salir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setBorder(null);
        btn_salir.setPreferredSize(new java.awt.Dimension(70, 20));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, 23));

        btn_limpiar.setText("limpiar");
        btn_limpiar.setBorder(null);
        btn_limpiar.setPreferredSize(new java.awt.Dimension(80, 70));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 90, 23));

        jLabel4.setText("ver 1.0");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/candadocerrado.png"))); // NOI18N
        getContentPane().add(jcMousePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 30, 30));

        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/user.png"))); // NOI18N
        getContentPane().add(jcMousePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 30, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_pass.setEnabled(true);
            txt_pass.requestFocus();
        }
    }//GEN-LAST:event_txt_userKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        //evento clic enter y pasar al siguiente objeto
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            //enfocar en el siguiente boton
            btn_acceder.setEnabled(true);
            //btn_acceder.requestFocus();
            
            //clic al pulsar enter
            btn_acceder.doClick();
        }
    }//GEN-LAST:event_txt_passKeyPressed

    private void txt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyTyped
        //Denegar escritura de nros en campo de caracter
        if(Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txt_userKeyTyped

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        //Metodos --> crear metodos

        //Limpiar cuadros
        limpiar_txt();

        //des-hab botones
        deshabilitar_botones();
        habilitar_botones();

        //des-hab txt
        deshabilitar_txt();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        UIManager.put("OptionPane.yesButtonText","Si");
        UIManager.put("OptionPane.noButtonText","No");

        EventQueue.invokeLater(()->{
            int cerrar_ventana = JOptionPane.showConfirmDialog(null, "Deseas salir del sistema?","Atencion",JOptionPane.YES_NO_OPTION);
            if (cerrar_ventana == JOptionPane.YES_OPTION){
                System.exit(0);
                //dispose();
            }
        });
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_accederKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_accederKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_accederKeyPressed

    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed
        String usuario, password; //declarando variables
        usuario = txt_user.getText(); //estirando datos del jtxbox
        password = txt_pass.getText();
        if ("admin".equals(usuario)&&"123".equals(password)){
            JOptionPane.showMessageDialog(null, "Bienvenido al sistema LP1","Datos correctos",JOptionPane.INFORMATION_MESSAGE);
            //Mensaje tipo informacion
            new principal().setVisible(true); //mostrando en pantalla "principal"
            this.setVisible(false); //ocultando menu
        }else{
            //mensaje de alerta
            JOptionPane.showMessageDialog(null, "Acceso denegado","Datos incorrectos",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_accederActionPerformed

    private void label_fechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_label_fechaPropertyChange

    }//GEN-LAST:event_label_fechaPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acceder;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jTitulo;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private javax.swing.JLabel label_fecha;
    private javax.swing.JLabel label_hora;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    private void limpiar_txt() {
    this.txt_user.setText("");
    this.txt_pass.setText("");
    }

    private void deshabilitar_botones() {
        // no sirve (ignorar)--> throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    this.btn_limpiar.setEnabled(false);
    }

    private void habilitar_botones() {
    //this.btn_limpiar.setEnabled(true);
    }

    private void deshabilitar_txt() {
    //    this.txt_pass.setEnabled(false);
    }
}
